version: '3.8'

services:
  # Neo4j Memory - Development Memory Service for Project Initializer
  # Serves all development projects with unusual ports to avoid conflicts
  dev-memory:
    image: docker.io/neo4j:5.13
    container_name: dev-project-memory
    environment:
      NEO4J_AUTH: neo4j/devmemorypass
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      # Memory settings (uncomment for production)
      #NEO4J_dbms_memory_heap_initial_size: 256m
      #NEO4J_dbms_memory_heap_max_size: 512m
    ports:
      - "9475:7474"   # HTTP interface (Web UI) - Unusual port
      - "9688:7687"   # Bolt protocol (MCP connection) - Unusual port
    volumes:
      - dev-memory-data:/data
      - dev-memory-backups:/backups
      - ./import:/var/lib/neo4j/import  # For backup/restore operations
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - dev-tools-network

volumes:
  dev-memory-data:
    driver: local
  dev-memory-backups:
    driver: local

networks:
  dev-tools-network:
    driver: bridge
    name: dev-tools-network

# Usage:
# 1. Start: docker-compose up -d
# 2. Stop: docker-compose down
# 3. View logs: docker-compose logs -f dev-memory
# 4. Access Web UI: http://localhost:9475 (unusual port)
# 5. Bolt connection: neo4j://localhost:9688 (unusual port)
# 6. Credentials: neo4j/devmemorypass